# Site settings
title: lastNPE.org - your last NullPointerException
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Develop NullPointerException free Java code with null analysis from Eclipse.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.lastnpe.org"
twitter_username: vorburger
github_username:  lastnpe

# Build settings
markdown: kramdown
permalink: pretty

# https://help.github.com/articles/configuring-jekyll/
#github: [metadata]
# kramdown:
#   input: GFM
#   hard_wrap: false
# gems:
#   - jekyll-coffeescript
#   - jekyll-paginate

# TODO
# pygments: true
